baseURL = 'https://hyaline.systems/'
languageCode = 'en-us'
title = 'hyaline.systems'
theme = "hyaline-theme"

# Site parameters
[params]

# Sub title
subtitle = ''

# Description
description = ''

# Menu
[[menu.main]]
name = "hyaline.systems"
url = "/"
weight = 1

[[menu.main]]
name = "blog"
url = "/posts"
weight = 2
